# Generated by Django 4.1.5 on 2025-10-16 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activity_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sedentary", "Sedentary"),
                    ("light", "Lightly active"),
                    ("moderate", "Moderately active"),
                    ("active", "Active"),
                    ("very_active", "Very active"),
                ],
                max_length=20,
                null=True,
                verbose_name="activity level",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="address"),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="birth date"),
        ),
        migrations.AddField(
            model_name="user",
            name="clinic_address",
            field=models.TextField(
                blank=True, null=True, verbose_name="clinic address"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                null=True,
                verbose_name="gender",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weight_loss", "Weight Loss"),
                    ("weight_gain", "Weight Gain"),
                    ("maintenance", "Maintenance"),
                    ("fitness", "Fitness"),
                ],
                max_length=20,
                null=True,
                verbose_name="goal",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="height_cm",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(250),
                ],
                verbose_name="height (cm)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="license_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="license number"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="national_id",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="national id",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="phone number"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="specialty",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="specialty"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="weight_kg",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(20),
                    django.core.validators.MaxValueValidator(300),
                ],
                verbose_name="weight (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("PATIENT", "Patient"),
                    ("DOCTOR", "Doctor"),
                    ("ADMIN", "Admin"),
                ],
                default="PATIENT",
                max_length=10,
                verbose_name="role",
            ),
        ),
    ]
